# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import edit_distance as module_0


def test_case_0():
    str_0 = "{q'\nW@spbXLSOke#EL,"
    var_0 = module_0.calculate_edit_distance(str_0, str_0)


def test_case_1():
    str_0 = ""
    var_0 = module_0.calculate_edit_distance(str_0, str_0)


def test_case_2():
    str_0 = ""
    str_1 = "K&}{)[eA!"
    var_0 = module_0.calculate_edit_distance(str_0, str_1)


def test_case_3():
    str_0 = "[w"
    str_1 = "K&}{)[A!"
    var_0 = module_0.calculate_edit_distance(str_0, str_1)


def test_case_4():
    str_0 = "do]k1N.r7Si<G&T"
    str_1 = "D"
    var_0 = module_0.calculate_edit_distance(str_0, str_1)


def test_case_5():
    str_0 = "{q'\nW@spbXLSOke#EL,"
    var_0 = module_0.calculate_edit_distance(str_0, str_0)
    var_1 = module_0.calculate_edit_distance(str_0, str_0)
