# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import word_squares as module_0


def test_case_0():
    str_0 = '%o$(o7&"$yW\rN3^be'
    var_0 = module_0.word_squares(str_0)


def test_case_1():
    dict_0 = {}
    var_0 = module_0.word_squares(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "ll"
    set_0 = {str_0, str_0, str_0}
    var_0 = module_0.word_squares(set_0)
    bytes_0 = b"\xd0 \xfc\xa6UK\xdc\xafJ\xa31\xbd\\\xa8Q\x9cit"
    module_0.word_squares(bytes_0)


def test_case_3():
    str_0 = "?<:&"
    set_0 = {str_0, str_0}
    var_0 = module_0.word_squares(set_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    module_0.word_squares(none_type_0)
