# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import longest_common_prefix as module_0


def test_case_0():
    str_0 = "?"
    var_0 = module_0.find_longest_common_prefix(str_0)
    assert var_0 == "?"


def test_case_1():
    str_0 = "?"
    list_0 = [str_0, str_0]
    list_1 = [str_0, list_0, list_0]
    var_0 = module_0.find_longest_common_prefix(list_1)
    assert var_0 == "?"
    var_1 = module_0.find_longest_common_prefix(str_0)
    assert var_1 == "?"


def test_case_2():
    tuple_0 = ()
    list_0 = [tuple_0, tuple_0]
    var_0 = module_0.find_longest_common_prefix(list_0)
    assert var_0 == ""


def test_case_3():
    str_0 = "0^f{1~cTp!KC\tl"
    list_0 = [str_0]
    var_0 = module_0.find_longest_common_prefix(list_0)
    assert var_0 == "0^f{1~cTp!KC\tl"
    var_1 = module_0.find_longest_common_prefix_reduce(list_0)
    assert var_1 == "0^f{1~cTp!KC\tl"
    var_2 = module_0.find_longest_common_prefix(var_1)
    assert var_2 == ""


def test_case_4():
    str_0 = ""
    var_0 = module_0.find_longest_common_prefix(str_0)
    assert var_0 == ""


def test_case_5():
    str_0 = '9#7#v3d"k5~t'
    var_0 = module_0.find_longest_common_prefix_reduce(str_0)
    assert var_0 == ""


def test_case_6():
    str_0 = ""
    var_0 = module_0.find_longest_common_prefix_reduce(str_0)
    assert var_0 == ""


def test_case_7():
    str_0 = "bb"
    var_0 = module_0.find_longest_common_prefix_reduce(str_0)
    assert var_0 == "b"
