# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import depth_first_search as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "aqELL5X>"
    module_0.depth_first_search(str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    var_0 = module_0.depth_first_search(list_0, list_0, list_0)
    str_0 = "aqELL5X>"
    module_0.depth_first_search(str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 2627
    module_0.depth_first_search(int_0, int_0, int_0)


def test_case_3():
    str_0 = "ln4Ps&V!`]"
    bool_0 = False
    tuple_0 = (bool_0, bool_0, str_0)
    var_0 = module_0.depth_first_search(str_0, tuple_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    list_0 = []
    str_0 = "l"
    bool_0 = False
    tuple_0 = (bool_0, bool_0, str_0)
    var_0 = module_0.depth_first_search(str_0, tuple_0, str_0)
    int_0 = -957
    module_0.depth_first_search(var_0, list_0, int_0)
