# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import hamming_ops as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -1504
    var_0 = module_0.hamming_weight(int_0)
    assert var_0 == 6
    var_1 = module_0.hamming_distance(int_0, int_0)
    assert var_1 == 0
    var_2 = module_0.hamming_distance(int_0, int_0)
    assert var_2 == 0
    bytes_0 = b"\x88\x91@\xea\xde"
    var_3 = module_0.hamming_weight(var_2)
    assert var_3 == 0
    var_4 = module_0.hamming_distance(var_3, var_1)
    assert var_4 == 0
    int_1 = -3634
    module_0.hamming_distance(bytes_0, int_1)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "G:@x'\x0cI"
    module_0.hamming_weight(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.hamming_distance(none_type_0, none_type_0)
