# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import breadth_first_search as module_0
import collections as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xfe\xe39\x076\xde\xd8:\xa7`\xca\xca\xc6\xa8\x84n"
    module_0.breadth_first_search(bytes_0, bytes_0, bytes_0)


def test_case_1():
    deque_0 = module_1.deque()
    var_0 = module_0.breadth_first_search(deque_0, deque_0, deque_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\x81\x8c=\x84\xa7[xQ\xf4\xe6\xe4\xf4"
    module_0.breadth_first_search_graph(bytes_0, bytes_0)
