# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mergesort as module_0


def test_case_0():
    str_0 = "><*Pk1VRp"
    var_0 = module_0.mergesort(str_0)


def test_case_1():
    str_0 = "Z$=wytH\x0b_@r\n=NN!w"
    var_0 = module_0.mergesort(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 3
    module_0.mergesort(int_0)
