# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import priority_queue1 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    priority_queue_0 = module_0.PriorityQueue()
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    var_0 = priority_queue_0.add_task(none_type_0)
    var_0.pop_task()


def test_case_1():
    priority_queue_0 = module_0.PriorityQueue()
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    priority_queue_1 = module_0.PriorityQueue()
    var_0 = priority_queue_1.add_task(priority_queue_0)
    assert len(module_0.PriorityQueue.pq) == 2


def test_case_2():
    none_type_0 = None
    priority_queue_0 = module_0.PriorityQueue()
    assert len(module_0.PriorityQueue.pq) == 2
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    priority_queue_0.set_priority(none_type_0, priority_queue_0)


def test_case_3():
    none_type_0 = None
    priority_queue_0 = module_0.PriorityQueue()
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    var_0 = priority_queue_0.add_task(none_type_0)
    priority_queue_1 = module_0.PriorityQueue()
    var_1 = priority_queue_1.set_priority(none_type_0)
    none_type_1 = None
    var_2 = priority_queue_0.remove_task(none_type_1)
    assert len(module_0.PriorityQueue.mapper) == 8


def test_case_4():
    none_type_0 = None
    priority_queue_0 = module_0.PriorityQueue()
    assert len(module_0.PriorityQueue.mapper) == 8
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    var_0 = priority_queue_0.set_priority(none_type_0)


def test_case_5():
    none_type_0 = None
    priority_queue_0 = module_0.PriorityQueue()
    assert len(module_0.PriorityQueue.mapper) == 8
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    var_0 = priority_queue_0.set_priority(none_type_0)
    priority_queue_0.pop_task()


def test_case_6():
    none_type_0 = None
    priority_queue_0 = module_0.PriorityQueue()
    assert len(module_0.PriorityQueue.mapper) == 8
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    var_0 = priority_queue_0.set_priority(none_type_0)
    priority_queue_0.pop_task()


@pytest.mark.xfail(strict=True)
def test_case_7():
    none_type_0 = None
    priority_queue_0 = module_0.PriorityQueue()
    assert len(module_0.PriorityQueue.mapper) == 8
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    priority_queue_1 = module_0.PriorityQueue()
    priority_queue_0.remove_task(none_type_0)
    var_0 = priority_queue_1.pop_task()


def test_case_8():
    priority_queue_0 = module_0.PriorityQueue()
    assert len(module_0.PriorityQueue.mapper) == 8
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
    priority_queue_0.pop_task()


def test_case_9():
    priority_queue_0 = module_0.PriorityQueue()
    assert module_0.PriorityQueue.REMOVED == "__removed-task__"
