# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import heapsort as module_0


def test_case_0():
    int_0 = 3393
    list_0 = [int_0, int_0]
    var_0 = module_0.heap_sort(list_0)


def test_case_1():
    list_0 = []
    var_0 = module_0.heap_sort(list_0)


def test_case_2():
    str_0 = "h*VBS@s-bNQCP<n@146"
    var_0 = module_0.max_heap_sort(str_0)


def test_case_3():
    list_0 = []
    var_0 = module_0.custom_heap_sort(list_0)


def test_case_4():
    str_0 = "h*VBS@s-bNQCP<n@G146"
    list_0 = [str_0, str_0]
    var_0 = module_0.heap_sort(list_0)
    var_1 = module_0.custom_heap_sort(list_0)
    var_2 = module_0.heap_sort(list_0)
    var_3 = module_0.max_heap_sort(str_0)


def test_case_5():
    int_0 = 1137
    list_0 = [int_0, int_0, int_0, int_0, int_0]
    var_0 = module_0.custom_heap_sort(list_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    module_0.heap_sort(none_type_0)
