# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import rabin_karp_substring_search as module_0


def test_case_0():
    str_0 = "@i:X$}*\nkJ"
    var_0 = module_0.rabin_karp_find_substring(str_0, str_0)
    assert var_0 == 0


def test_case_1():
    str_0 = '#+8h\x0c[])#TaF$A[XK"8'
    str_1 = '#+8hY[])#TaFi$A[XK"8'
    var_0 = module_0.rabin_karp_find_substring(str_1, str_0)
    assert var_0 == -1
